name: Build Selene

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  build:
    strategy:
      matrix:
        include:
          # Android
          - name: android
            os: ubuntu-latest
            build-args: "--android-only"

          # macOS / iOS
          - name: macos_ios
            os: macos-latest
            build-args: "--apple-only"
            
          # Windows
          - name: windows-amd64
            os: windows-latest
    
    runs-on: ${{ matrix.os }}
    env:
      NDK_VERSION: '29.0.14033849'
      NDK_VERSION_DEPS: '27.0.12077973'
    name: Build ${{ matrix.name }}
    
    steps:
      - name: Clone repository
        run: |
          git clone https://${{ secrets.PULL_TOKEN }}@${{ secrets.REPO_URL }}.git .
        shell: bash
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Install Java
        if: runner.os == 'Linux'
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Android SDK
        if: runner.os == 'Linux'
        uses: android-actions/setup-android@v3

      - name: Install NDK
        if: runner.os == 'Linux'
        run: |
          echo "y" | sdkmanager --install "ndk;${{ env.NDK_VERSION }}"
          echo "y" | sdkmanager --install "ndk;${{ env.NDK_VERSION_DEPS }}"
      
      - name: Build with build.sh (Android/macOS/iOS)
        if: runner.os != 'Windows'
        continue-on-error: true
        run: |
          chmod +x build.sh
          ./build.sh ${{ matrix.build-args }}
        shell: bash
      
      - name: Build on Windows
        if: runner.os == 'Windows'
        continue-on-error: true
        shell: pwsh
        run: |
          $version = (Get-Content pubspec.yaml | Select-String '^version:' | ForEach-Object {$_ -replace 'version: ', ''}).trim()
          Write-Host "Building version: $version" -ForegroundColor Green
          flutter pub get
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Write-Host "Building Windows..." -ForegroundColor Blue
          flutter build windows --release
          Compress-Archive -Path build/windows/x64/runner/Release/* -DestinationPath "dist/selene-$version-windows-x64-portable.zip" -Force
          Write-Host "Windows build complete" -ForegroundColor Green
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: ${{ matrix.name }}-release-artifacts
          path: dist/*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/') && (success() || failure())
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts
      
      - name: Prepare release artifacts
        run: |
          mkdir -p release-files
          find all-artifacts -type f -exec cp {} release-files/ \;
          ls -lh release-files/
      
      - name: Get version from tag
        id: tag_version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.version }}
          name: Selene ${{ steps.tag_version.outputs.version }}
          files: release-files/*
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get Release Notes
        id: release_notes
        run: |
          RELEASE_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.tag_version.outputs.version }}")
          
          RELEASE_BODY=$(echo "$RELEASE_INFO" | python3 -c "import sys, json; data=json.load(sys.stdin); print(data.get('body', '') if 'body' in data else '')")
          
          {
            echo 'notes<<EOF'
            echo "$RELEASE_BODY"
            echo EOF
          } >> $GITHUB_OUTPUT
          
          echo "Release notes length: ${#RELEASE_BODY}"
      
      - name: Send Telegram notification
        if: success()
        env:
          CHANNEL_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          if [ ! -d "release-files" ] || [ -z "$(ls -A release-files)" ]; then
            echo "No release files found"
            exit 0
          fi
          
          VERSION="${{ steps.tag_version.outputs.version }}"
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/tag/${VERSION}"
          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          
          RELEASE_NOTES=$(cat << 'NOTES_EOF'
          ${{ steps.release_notes.outputs.notes }}
          NOTES_EOF
          )
          
          echo "开始上传文件到 Telegram..."
          
          FILE_IDS=()
          MESSAGE_IDS=()
          for file in release-files/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              
              if [[ ! "$filename" =~ \.(apk|ipa)$ ]]; then
                echo "跳过文件: $filename"
                continue
              fi
              
              RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendDocument" \
                -F "chat_id=${CHANNEL_ID}" \
                -F "document=@${file}")
              
              FILE_ID=$(echo "$RESPONSE" | python3 -c "import sys, json; data=json.load(sys.stdin); print(data['result']['document']['file_id'] if 'result' in data else '')" 2>/dev/null)
              MESSAGE_ID=$(echo "$RESPONSE" | python3 -c "import sys, json; data=json.load(sys.stdin); print(data['result']['message_id'] if 'result' in data else '')" 2>/dev/null)
              
              if [ ! -z "$FILE_ID" ]; then
                FILE_IDS+=("$FILE_ID")
                MESSAGE_IDS+=("$MESSAGE_ID")
              fi
              
              sleep 1
            fi
          done
          
          if [ ${#FILE_IDS[@]} -gt 0 ]; then
            echo "准备发送 media group..."
            FILE_IDS_JSON=$(printf '%s\n' "${FILE_IDS[@]}" | jq -R . | jq -s .) 
            export FILE_IDS_JSON VERSION RELEASE_URL TIMESTAMP RELEASE_NOTES
            
            python3 << 'PYEOF' > media.json
          import json
          import os
          
          file_ids = json.loads(os.environ['FILE_IDS_JSON'])
          version = os.environ['VERSION']
          release_url = os.environ['RELEASE_URL']
          timestamp = os.environ['TIMESTAMP']
          release_notes = os.environ.get('RELEASE_NOTES', '').strip()
          
          message = f"""🎉 *Selene 新版本发布*"""
          
          if release_notes:
              if len(release_notes) > 800:
                  release_notes = release_notes[:800] + "..."
              message += f"\n\n📝 *更新说明*:\n{release_notes}"
          
          message += f"""
          
          📦 版本: `{version}`
          🔗 GitHub: [点击查看]({release_url})
          💡 Windows 及 MacOS 包请自行前往 Releases 处下载
          🕐 发布于: {timestamp}"""
          
          media = []
          for idx, file_id in enumerate(file_ids):
              item = {
                  "type": "document",
                  "media": file_id
              }
              if idx == len(file_ids) - 1:
                  item["caption"] = message
                  item["parse_mode"] = "Markdown"
              media.append(item)
          
          print(json.dumps(media))
          PYEOF
            
            curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup" \
              -H "Content-Type: application/json" \
              -d "{\"chat_id\":\"${CHANNEL_ID}\",\"media\":$(cat media.json)}"
            
            for msg_id in "${MESSAGE_IDS[@]}"; do
              curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/deleteMessage" \
                -d "chat_id=${CHANNEL_ID}" \
                -d "message_id=${msg_id}" > /dev/null
            done
          fi
        
  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
